# Generated by Django 5.2.3 on 2025-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='forum_adminuser',
        ),
    ]
